### Loading LIbrary

In [1]:
import numpy as np

## Creating numpy array

In [3]:
list1 = [2, 4 ,6, 8]
arr1 = np.array(list1)

In [5]:
print(arr1)

[2 4 6 8]


In [6]:
print(list1)

[2, 4, 6, 8]


In [7]:
type(list1)

list

In [8]:
type(arr1)

numpy.ndarray

In [11]:
list1 + 1

TypeError: can only concatenate list (not "int") to list

In [12]:
arr1+1

array([3, 5, 7, 9])

In [13]:
# array from 2d list

list2 = [[9, 0, 4 ,6], 
         [4, 6 ,1, 1]]
arr2 = np.array(list2)

In [14]:
arr2

array([[9, 0, 4, 6],
       [4, 6, 1, 1]])

In [16]:
arr2 = np.array(list2, dtype = 'float')

In [17]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 1., 1.]])

In [25]:
arr2 = np.array(list2, dtype = 'int')
arr2

array([[9, 0, 4, 6],
       [4, 6, 1, 1]])

In [21]:
arr2 = np.array(list2, dtype = 'bool')
arr2

array([[ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [23]:
listt = arr1.tolist()
listt

[2, 4, 6, 8]

In [24]:
type(listt)

list

In [33]:
arr5 = np.array([2, 5 , 'y', 2], dtype = 'object')
arr5

array([2, 5, 'y', 2], dtype=object)

## 2. Array Dimensions

In [26]:
arr2

array([[9, 0, 4, 6],
       [4, 6, 1, 1]])

In [27]:
arr2.shape

(2, 4)

In [29]:
arr2.size

8

In [31]:
arr2.dtype

dtype('int64')

In [32]:
arr2.ndim

2

### 3. Specific element extraction

##### arr[start_index_row: end_index_row, start_index_col:end_index_col]

##### Rows

In [34]:
arr2

array([[9, 0, 4, 6],
       [4, 6, 1, 1]])

In [36]:
arr2[0:1, ]

array([[9, 0, 4, 6]])

In [37]:
arr2[0, ]

array([9, 0, 4, 6])

In [45]:
arr2[0]

array([9, 0, 4, 6])

In [38]:
arr2[:1, ]

array([[9, 0, 4, 6]])

In [40]:
arr2[:-1, ]

array([[9, 0, 4, 6]])

In [39]:
arr2[:2, ]

array([[9, 0, 4, 6],
       [4, 6, 1, 1]])

#### Columns

In [41]:
arr2[:, -1]

array([6, 1])

In [44]:
arr2[:, 0:2]

array([[9, 0],
       [4, 6]])

### Basic Statistics

In [46]:
arr2

array([[9, 0, 4, 6],
       [4, 6, 1, 1]])

In [47]:
arr2.min()

0

In [48]:
arr2.max()

9

In [49]:
arr2.sum()

31

In [50]:
arr2.mean()

3.875

In [51]:
arr2.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [52]:
np.median(arr2)

4.0

In [53]:
np.average(arr2)

3.875

In [54]:
np.var(arr2)

8.359375

### 6. Reshape and Flattening

In [63]:
arr2

array([[9, 0, 4, 6],
       [4, 6, 1, 1]])

In [64]:
arr2[0][0]

9

In [56]:
arr2.shape

(2, 4)

In [57]:
arr2.reshape(4, 2)

array([[9, 0],
       [4, 6],
       [4, 6],
       [1, 1]])

In [65]:
a = arr2.reshape(8)
a

array([9, 0, 4, 6, 4, 6, 1, 1])

In [66]:
a[0]

9

In [67]:
b = arr2.reshape(2,2, 2)
b

array([[[9, 0],
        [4, 6]],

       [[4, 6],
        [1, 1]]])

In [74]:
b = arr2.reshape(2,2, 2, 1, 1)
b

array([[[[[9]],

         [[0]]],


        [[[4]],

         [[6]]]],



       [[[[4]],

         [[6]]],


        [[[1]],

         [[1]]]]])

In [68]:
b[0][0][0]

9

In [60]:
arr2.reshape(1, 7)

ValueError: cannot reshape array of size 8 into shape (1,7)

## 7. Create random sequences

In [69]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.arange(1, 10, 5)

array([1, 6])

In [72]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [73]:
np.linspace(start = 1, stop= 10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [77]:
np.zeros([10, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [78]:
np.zeros([5])

array([0., 0., 0., 0., 0.])

In [80]:
np.zeros([5, 1,2])

array([[[0., 0.]],

       [[0., 0.]],

       [[0., 0.]],

       [[0., 0.]],

       [[0., 0.]]])

### 8. unique and item count

In [81]:
arr = [[1, 4, 5, 2 ,2, 5], 
       [4, 4, 1, 7, 4, 5]]

In [82]:
arr.unique

AttributeError: 'list' object has no attribute 'unique'

In [84]:
np.unique(arr, return_counts = True)

(array([1, 2, 4, 5, 7]), array([2, 2, 4, 3, 1]))

In [85]:
unique_element_var, count_element_var = np.unique(arr, return_counts = True)

In [86]:
unique_element_var

array([1, 2, 4, 5, 7])

In [87]:
count_element_var

array([2, 2, 4, 3, 1])